function PlayerMain() {
    let nums = readline();  //array de 1 a 100
    let list = nums.split(",");
    parseInt(list);


    //Para debug
    console.error("My Debug Message");
    console.log(resolver(list));

    function resolver(valor) {
        let lista = []
        lista.push(valor)

        for (let index = 0; index < lista.length; index++) {
            if (lista[index] % )
            
        }

    }
}

PlayerMain();